-- phpMyAdmin SQL Dump
-- version 5.1.1deb5ubuntu1
-- https://www.phpmyadmin.net/
--
-- Hôte : localhost:3306
-- Généré le : ven. 05 mai 2023 à 20:46
-- Version du serveur : 10.6.12-MariaDB-0ubuntu0.22.04.1
-- Version de PHP : 8.1.2-1ubuntu2.11

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Base de données : `super_week`
--

-- --------------------------------------------------------

--
-- Structure de la table `book`
--

CREATE TABLE `book` (
  `id` int(11) NOT NULL,
  `title` varchar(255) NOT NULL,
  `content` text NOT NULL,
  `id_user` int(11) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Déchargement des données de la table `book`
--

INSERT INTO `book` (`id`, `title`, `content`, `id_user`) VALUES
(1, 'Eius quia et.', 'Omnis sed et excepturi dolor adipisci quisquam dignissimos animi ullam a fugiat dolorum quos odio laborum quis illum similique dolorum eligendi quibusdam eum voluptas eaque et quae impedit dolor mollitia modi error voluptas consequatur nihil qui ad animi possimus iste voluptatem consectetur vel aut est aperiam nisi distinctio quia iste adipisci nesciunt aliquam quae accusamus tempore quos officia doloribus repellendus et id eveniet omnis maxime sunt nam soluta vero commodi aut nihil ut recusandae incidunt libero debitis sint inventore aut corporis reprehenderit ut sunt ratione molestiae et doloribus placeat earum sapiente ad a nostrum qui quia quo eligendi quasi nobis neque aspernatur et sit placeat blanditiis reprehenderit dolore ipsum in vel velit est enim quas voluptatem vitae at nemo iste iusto est rerum magni in quos expedita nulla accusantium eligendi quis ipsam sapiente voluptas velit aliquid voluptatibus et et ratione atque voluptatem nesciunt quia modi eveniet ipsam voluptatum similique nesciunt dolorem consectetur est rerum velit assumenda quaerat laudantium sunt autem atque neque soluta recusandae quaerat laborum est fugit tempora nihil doloremque soluta excepturi sequi quaerat et voluptatem dolorem architecto deserunt hic blanditiis et optio ipsam cupiditate omnis qui nobis quia ipsam saepe deserunt sit culpa possimus odio iusto labore eaque sed eaque nisi ullam temporibus officia aspernatur doloremque veniam possimus et consequatur soluta molestiae id maiores accusantium porro temporibus nostrum aut saepe officiis tempora vero consectetur et animi qui cumque quisquam inventore quae unde sed enim sit a mollitia ea qui aliquam consequatur in aut modi enim asperiores qui eveniet aut et quia eius harum quas et dolor fugiat qui harum ut aut.', 3),
(2, 'Aut autem aperiam.', 'Et quasi eos fuga laudantium atque numquam maiores quisquam quibusdam assumenda ipsa ut culpa animi nihil eveniet corporis aut perspiciatis aperiam et aut ipsa aut qui commodi porro delectus laborum molestiae hic vitae aut et soluta aut ea atque nihil rem asperiores voluptatem atque consequatur id laborum sed atque ut illo modi consectetur reprehenderit corrupti eveniet est asperiores non fuga eveniet tempore facere non dolorem voluptas sit sapiente sunt sapiente voluptate quae consequatur sit suscipit cum ratione officiis ea dolorem nesciunt laborum omnis nobis voluptatibus laudantium beatae modi velit et odio quaerat et est cumque et est explicabo voluptas quos reiciendis iusto facilis iusto est minus animi atque consequatur ipsum inventore nobis sed incidunt omnis adipisci eum explicabo rerum delectus sed porro nam mollitia earum ad vitae ipsum dolores expedita consequuntur necessitatibus quia ut doloremque et est aut et cum magnam dignissimos quo incidunt iste nam iusto sunt magnam quibusdam beatae aut repellendus et incidunt voluptatem neque velit ea nihil eos nemo cum ut reprehenderit voluptas autem enim voluptate animi est autem odit placeat unde et error vero veritatis ut impedit ducimus quis hic magni veniam eum sed dignissimos et nihil omnis est corrupti neque enim ut voluptatem eos consectetur et id et vel sit error enim est porro ut explicabo nihil unde consequatur voluptatem architecto ut ex voluptatem magni perferendis molestiae qui magni sed alias quod voluptatem sit nam est quasi totam aut voluptas sunt enim nulla architecto atque et molestias commodi debitis expedita laudantium laudantium fugit qui rerum et beatae saepe aliquid dolores ut perferendis ea rerum praesentium saepe quis omnis.', 16),
(3, 'Odio nesciunt.', 'Reprehenderit consequatur dolor quos excepturi suscipit repellat dolorem nostrum a nulla nulla id iure quia quibusdam aliquam rerum et voluptatem debitis fugit soluta non fugiat impedit repudiandae eius et animi id voluptatibus aliquam consequatur explicabo quod provident impedit corrupti nam ut minus beatae et soluta optio aperiam voluptas pariatur maxime tempora quam voluptatem in eos reiciendis occaecati quia consequuntur accusamus at ut voluptatem placeat esse et minus tenetur cumque deleniti ut eos minus laboriosam alias voluptas distinctio quam quia sapiente et ea molestiae necessitatibus omnis eveniet totam quaerat quia vel ullam dolore voluptas temporibus sed sapiente et repudiandae atque minus doloremque illo sunt enim autem voluptas iure qui sed laborum ex dignissimos eligendi ipsa enim est ipsum dolorem dolorum beatae eaque laboriosam officia non et laudantium fugiat autem autem accusamus omnis aut est rerum voluptas sequi sed molestiae rerum ea doloremque ut non dolor corrupti dignissimos fuga in rerum at quisquam commodi sequi pariatur saepe nostrum ex laborum voluptates ut amet libero et beatae expedita dolorum quia mollitia a dignissimos ut velit deserunt repellendus eum qui quaerat et praesentium et repellat qui voluptatum illum officiis et quasi pariatur consequatur atque et placeat neque vitae consectetur enim consequatur provident commodi quia labore sed aut velit dolore libero doloremque consequuntur quo illum atque quia itaque ullam ut odit quasi nesciunt ad fugiat dolorum veniam nihil occaecati modi repellat dolores officia numquam.', 7),
(4, 'Qui dicta eos.', 'In consequatur necessitatibus quas quasi voluptas numquam accusamus eos debitis quod est non omnis sapiente ullam est sed totam non eum autem id eos hic delectus est consequuntur ipsam explicabo sit nam quae veniam aliquid soluta velit hic voluptatem vel et soluta distinctio veritatis illum voluptas dolor modi sed rerum ea voluptas quis nisi et amet et nostrum modi et tenetur sint sunt quia est adipisci qui laboriosam harum cupiditate aut aut molestiae sed consequatur asperiores laborum nobis officia dicta dolorum nihil eligendi nemo enim est alias fugit ullam ut corporis illo a cum veritatis dolores ut ratione ipsum aut consequuntur distinctio placeat accusamus labore quis ratione ipsam porro ut quod sed quidem esse et consequatur earum commodi pariatur aut pariatur vitae natus aperiam eaque eaque nobis dicta similique voluptatem et et rerum officia non ut eos vitae illum quisquam et adipisci sed et ut nemo libero quis id qui sed aperiam eveniet similique dicta impedit quia nesciunt quia neque quos optio molestiae ab exercitationem perferendis hic et quis qui numquam a placeat voluptatem doloribus voluptatem dolor numquam aut quasi nisi autem enim asperiores laboriosam fugit consectetur nulla labore cum aliquid tenetur rem veritatis doloremque aut eos quae distinctio et dolorem illum non itaque explicabo adipisci laborum.', 9),
(5, 'Rerum est quibusdam.', 'Laboriosam sequi est aliquam ratione ut non enim est voluptatum deserunt illum doloribus voluptatum qui voluptates in ullam non iste provident quisquam mollitia non culpa eum illo molestiae aut quos ut voluptate aspernatur ab nostrum quae et numquam rerum animi nam iste error aliquid excepturi distinctio ut vero vitae beatae reprehenderit temporibus dolorem qui consequuntur quis aut laboriosam eaque neque culpa soluta eveniet maxime est voluptates tempora qui dolor quam ducimus qui voluptate ratione voluptatem voluptates perspiciatis et impedit eos et ex rerum temporibus aut molestiae qui cumque et eum veritatis quidem in est dolores nulla sit veritatis dolor et est neque quia numquam ad adipisci sunt animi necessitatibus veniam quod voluptatem voluptatem eveniet sunt est in nesciunt sit commodi facilis repellat molestias modi hic inventore aut et provident doloremque veritatis adipisci dolorum dolorem eos repudiandae beatae aperiam omnis repellat et ipsa rem delectus autem nihil placeat officiis quasi ad aut ex unde assumenda sapiente nihil optio ad quasi debitis enim quo quis est qui quos laborum asperiores et mollitia voluptatem ut nihil saepe veniam non iste velit facere corporis ad dolor accusamus et voluptatem odit rerum possimus maxime laboriosam nesciunt quae veniam minus a earum iste dolorum sint non reprehenderit et eaque sapiente illum mollitia quia facilis iure eveniet a culpa aliquam.', 15),
(6, 'Et cupiditate aut.', 'Aspernatur molestiae dignissimos aut architecto similique ut et accusantium iusto fuga veniam accusantium quisquam aperiam et eos eveniet quis minima dolores rerum aliquid enim dolorum quasi aspernatur dolor quo assumenda inventore mollitia et consectetur autem corrupti veniam harum aspernatur numquam rerum aut est quis perferendis et dicta deleniti ipsum facilis dolorem nisi eum consequatur quisquam ratione suscipit temporibus accusantium repellat laborum ut omnis in quos recusandae veritatis id cupiditate facere qui hic labore quaerat ut sit ea porro eius eos molestias nulla quod fugiat optio aliquid magni et natus voluptatum voluptas perferendis eum nihil quisquam fuga nulla quaerat aut ab quod ad in et est velit aut similique repellat sapiente et ipsum dolor eaque voluptatem expedita sequi ipsum reiciendis sit voluptatibus rerum ab velit distinctio debitis adipisci nobis esse non quibusdam doloremque quidem perspiciatis est explicabo nihil id eum blanditiis eligendi minus rerum dolores esse labore quidem ipsa quia quod aut nihil placeat exercitationem voluptate rem est alias voluptatem est dolor reprehenderit repellendus et ea inventore neque molestias error suscipit cupiditate et voluptatem et dolores et omnis repellat et.', 12),
(7, 'Itaque modi.', 'Libero voluptatibus est eos itaque sunt dolor iste possimus incidunt itaque asperiores ullam quo voluptatem repellat et laudantium veritatis numquam quidem praesentium dolorem sit eum sed ea quod nihil qui voluptas maiores harum inventore est quo aut omnis dolores temporibus sed aut sequi quis quia magni temporibus dolor commodi suscipit maxime nisi tempore cumque vitae nam autem repellat qui incidunt qui dolorem amet quod aut eaque aut et reiciendis fugiat eveniet veniam sapiente commodi cupiditate fuga laborum velit eius dolore dolores et provident dolore rem non excepturi voluptatem ratione et sed nobis consequatur beatae non et dolorem facere sit sed veritatis libero dolor ratione nihil dicta qui eaque debitis neque fugit autem maiores quaerat tempora culpa sit quas quis minus temporibus sunt voluptates eaque aut blanditiis nihil et ipsum eveniet occaecati vel nihil et aut voluptates non voluptas et molestiae perspiciatis et cum facilis in distinctio qui nisi repellendus est dolor dolorem voluptatum asperiores amet exercitationem est amet accusamus dolor aut esse a veritatis facere ipsa itaque voluptates a debitis consectetur provident aliquam laborum quo expedita accusamus saepe eos praesentium laboriosam eaque nihil maxime ducimus at fuga est harum ipsum sed maxime quis nobis ut deserunt numquam delectus architecto.', 19),
(8, 'Aut vel asperiores.', 'Inventore et eveniet temporibus libero qui qui totam soluta ipsa rem laudantium vel dolorum eaque aliquid culpa fuga voluptate delectus velit molestias aliquam aspernatur maxime consequuntur autem animi tempore vel exercitationem velit distinctio aut inventore dicta culpa ipsum officiis et molestias laborum eum et consequuntur est sapiente commodi error quia laudantium voluptatem recusandae cupiditate recusandae dolorem soluta aut aut molestias non et sint perferendis id velit distinctio et quod sunt doloribus eum consequuntur consequatur repudiandae quis excepturi quos quam consequatur dicta sint asperiores et ducimus repudiandae sit nemo minus illum et atque ducimus odio quas dolores est nisi nulla aut eveniet non molestiae eaque perspiciatis laborum blanditiis animi non beatae quas nihil incidunt odit nisi molestiae fuga enim dicta eum blanditiis enim et eveniet vitae dolores aliquam enim aut pariatur odio adipisci repellendus sed et placeat placeat non eum est velit et velit ut cumque deserunt non libero maiores velit sint voluptas quos labore beatae dolores molestiae rerum veritatis aut quae velit earum maxime omnis voluptas magni sed quo aut et qui impedit incidunt dolorum ab molestiae quia dolores.', 13),
(9, 'Quaerat praesentium.', 'Laudantium molestiae pariatur alias non accusantium sint nam pariatur mollitia ut qui perferendis dolorem harum accusantium eligendi quibusdam veritatis ut dolor ipsam occaecati iure repellendus molestiae eaque quis explicabo quaerat reiciendis eum et harum et aut impedit possimus temporibus iste consequatur et ut unde quia cumque ipsum in deleniti porro inventore aliquam voluptas veritatis et reprehenderit eveniet mollitia numquam qui delectus alias maxime asperiores ea inventore possimus eveniet a voluptatem maxime quo voluptatem voluptates odio aut eveniet exercitationem voluptas illo dolor sunt sit voluptatibus libero reprehenderit expedita inventore rerum molestiae temporibus animi quam possimus molestias qui asperiores ipsum exercitationem rem aut in temporibus sunt id veniam vero quis repellat cum unde facilis ex dolor reprehenderit sed non sint consequatur consequatur et dolor consequuntur hic dolorum animi eligendi.', 10),
(10, 'Non repellat quo et.', 'Alias aut sunt veniam ipsum et et architecto enim cupiditate nostrum aut corrupti rem et similique eaque qui neque perspiciatis rerum laudantium ipsa et quam sunt doloribus similique vitae molestiae similique occaecati optio tempore iste mollitia et voluptatum voluptas corrupti voluptas voluptatem et distinctio voluptatem autem et autem voluptatem minima incidunt quo ut et et est in maiores aperiam earum nostrum ipsam ratione aspernatur consequatur possimus reprehenderit excepturi cupiditate quisquam sit ut suscipit error quas nesciunt ipsa eaque ut optio quae harum mollitia eos est rerum soluta expedita eveniet consectetur magni aliquid rem nam occaecati ut culpa amet iste repellendus saepe fugit odit est enim doloremque autem itaque et expedita et vero quasi libero molestiae voluptatum aut nulla soluta praesentium aperiam quod neque earum sint iusto et sapiente iste veritatis dolorem cupiditate praesentium dolorum est quis accusamus veniam doloremque omnis perferendis aliquam praesentium enim ut a sunt amet ipsam nesciunt reprehenderit harum fuga officia adipisci et dolores laboriosam quae perspiciatis quisquam commodi necessitatibus voluptates rerum et sunt culpa nostrum minus laborum impedit explicabo ratione quasi itaque neque officiis molestias cupiditate culpa sunt voluptatibus saepe accusamus magnam eveniet consequuntur eaque corrupti eum sunt minima repellat aut quam ad illo totam corporis laboriosam debitis atque labore accusantium amet aliquid nemo vel qui neque sint blanditiis est itaque quos eos quos aperiam rerum doloremque dolorum quaerat sit eius vitae qui aut dolorem eligendi cum iste adipisci quis quas magni ea nobis dolorem quis qui at aut omnis quo voluptas aut eum explicabo non beatae ullam ut vel sunt similique est aut aut ratione quisquam saepe voluptas deleniti non aut ad delectus odio.', 7),
(11, 'Ad itaque fugit non.', 'Adipisci et voluptates provident alias quia rerum facere autem placeat facilis aut nihil ipsum suscipit ut facere id assumenda et magnam dolorem aliquid veniam ut rem dolores ex quas ut aut et incidunt dolorem autem omnis voluptas similique voluptatem nemo tempora et quo dolorem sed animi autem aut quidem a voluptate et voluptatem quibusdam adipisci aut et voluptatem asperiores ut animi modi accusamus natus et iste sed nisi architecto ad libero et vero eveniet temporibus maiores labore temporibus vel soluta quam repudiandae aperiam eius ipsa et dicta ex nesciunt vel ex numquam ipsam aperiam amet laborum laborum aut odio qui laboriosam perspiciatis consequatur voluptas non ut ea repellat fugiat ducimus accusantium voluptas laboriosam enim quo nisi est molestiae eum natus sed dolorum dolor ab eos corrupti voluptatem minima dolorum perspiciatis dolorum tenetur error nostrum molestiae quia culpa distinctio dolores nihil ut voluptatem placeat dolorum rem nobis dolorem optio eum mollitia veritatis voluptatem nemo provident eius eligendi voluptas molestias quis optio iusto omnis dolorem dolorem magni deserunt id qui quia laborum id.', 15),
(12, 'Nihil praesentium.', 'Et fuga maiores amet itaque et voluptate quia commodi provident qui vel beatae in placeat et ut quisquam nisi et minima explicabo dolorem quas veritatis qui sequi veniam ipsam ea similique consequatur debitis autem enim neque minus ut sint ipsam fuga nisi officiis ea eius rerum nam autem et repellendus sed consequuntur qui debitis eveniet dolore exercitationem voluptatem harum maxime ea consectetur sapiente autem voluptas similique voluptatem deleniti et at sint temporibus inventore cumque iste labore maxime labore unde expedita quia debitis distinctio ullam et minus eos eveniet laudantium eveniet et optio dolorem maiores ad ab optio voluptas autem neque repellendus voluptas nobis et sint facere inventore vel rerum aut facilis laudantium ducimus ipsa molestiae voluptas et rerum iusto corrupti fugiat facere suscipit atque quas ut neque consequatur soluta est qui et qui at quisquam dolores fugiat illo odio nulla a accusantium sint illo recusandae quidem mollitia sed sunt dolores non atque vero et eligendi facilis perferendis quod voluptates consectetur est delectus sint beatae aut facere incidunt illo et et nemo quidem quisquam laborum voluptatem occaecati et modi ducimus autem rerum maiores dolor enim illo eligendi aspernatur suscipit unde nihil quisquam iste quas nostrum fuga quasi accusantium ut facere dolorem quidem qui laboriosam id quia unde ad autem sunt sint nemo accusamus esse placeat neque et corporis occaecati eveniet sed quia et occaecati sapiente aut et non.', 17),
(13, 'Sed facilis.', 'Vitae aut et quam id earum animi sint eaque et est delectus et id sunt beatae voluptate amet totam quia id eveniet fuga a deserunt sunt et non fuga sed blanditiis quia doloribus aut aperiam est et in dolores laborum autem beatae alias quia accusantium dolorum maiores et eius nobis autem voluptatem ut et ducimus impedit nihil rem ea provident sunt ut sit consequatur id facere impedit mollitia soluta qui officia dignissimos officiis dolorem expedita perferendis quaerat velit et ullam quo dolores quia harum eos nisi fuga itaque exercitationem voluptates earum distinctio et pariatur quisquam corrupti aut et facere doloribus architecto eum et consequuntur quas error in quaerat eveniet vitae et expedita accusantium ipsam eos dolores labore et id veniam quidem laborum qui voluptatem sequi nemo sit aut vel neque eum dolorem optio dolorem aut corrupti et aliquam vel dolor quis quia voluptatibus voluptate voluptatibus aut fuga quod a est labore eos sequi ad labore voluptatem qui voluptas reiciendis voluptatum odio eaque odit ut sint eveniet illo ut ullam voluptate omnis inventore ut officia ea voluptates tempora est repellendus laudantium aut necessitatibus earum ipsum ad nisi quia quo corporis dolores ratione distinctio laudantium maiores optio est dolores quis iure eaque est et laboriosam sint eos et voluptate asperiores delectus assumenda ut est sunt qui ad cum explicabo placeat et et dolorem debitis molestias.', 1),
(14, 'Reprehenderit id.', 'Et esse esse rerum ipsum aliquam nulla recusandae dolor sint tempora qui harum nulla dolorem numquam aut quos consequuntur eos cum unde reprehenderit est nam pariatur ea non expedita amet minima maxime hic rerum dolores et vel excepturi velit neque et iusto aut voluptatem et quia molestias voluptatum tempora modi et repellendus non aut iste esse deserunt non voluptas sunt qui sed voluptates est modi molestiae cupiditate totam culpa tempora culpa voluptatem inventore architecto maxime amet molestiae distinctio et voluptatibus beatae expedita provident excepturi non eveniet ullam vitae optio eaque libero voluptatem voluptas itaque perspiciatis ut voluptas fugiat voluptatem expedita consequatur corrupti ut rerum dolorem excepturi ea error non eveniet libero ut quas tempora inventore totam quae et culpa qui dolorem ut dolores eum ipsum repellat vitae odio sunt non perferendis dolorum laboriosam quisquam eligendi qui dolorum voluptatem ipsum qui nobis quia quisquam eius est ut laborum aliquid et temporibus voluptas laborum error eligendi fuga dicta et ut tenetur temporibus occaecati consequatur officia fugit aut eum esse fuga quo qui id autem molestiae odio itaque enim sint quis id quis veniam aut dignissimos ad ut est est reiciendis laudantium molestiae optio occaecati occaecati est est exercitationem unde minus esse rerum aut ut amet quo labore debitis officia dolorem qui id dolor ducimus asperiores earum repudiandae corporis fugit vel hic asperiores autem laudantium et sequi officia delectus at iste illo qui illum doloribus tempora vitae sit voluptas dolorem ab doloremque quia dolorem distinctio delectus cum asperiores sint molestiae tempore in ipsam omnis cum magnam et libero accusamus voluptas ut voluptatem quo voluptates ut tempore earum est totam dolorum commodi exercitationem.', 12),
(15, 'Quaerat cum.', 'Ratione quasi consequatur praesentium id ducimus consequatur dolorem culpa est dolores est molestiae sit sit perspiciatis voluptatem ut ex repellat quo ad amet rerum eligendi aut rerum quis quia at iste totam fugit qui provident ratione provident temporibus minus nostrum officia non nesciunt sapiente aut aut libero vero sequi at aut vel itaque dolorem voluptatum nam qui quidem et praesentium eum aspernatur iste minus deserunt quia tenetur nulla quae omnis et numquam non delectus quas quam eius possimus vero tempore beatae incidunt dolores error aut necessitatibus distinctio animi nemo fugiat cumque nesciunt earum incidunt quasi et vel optio esse asperiores est numquam tempore odit minima quas repellat sapiente natus velit asperiores distinctio et illo dolorem amet dolor reiciendis vel esse amet aliquid voluptatibus et aut unde officiis voluptatibus animi pariatur consequatur expedita quibusdam ipsam nihil pariatur ullam tenetur qui doloremque itaque quo sit reiciendis voluptatibus nostrum debitis ab voluptas est doloremque et rerum.', 3),
(16, 'Quae perspiciatis.', 'Cumque rerum iusto aut eligendi est fugit et excepturi quaerat ut ut modi optio magni omnis dolor commodi magnam nemo fugit sit dolore neque ipsam quo sit accusamus nihil voluptatem vel cumque ab tempore similique dolores et ut officia omnis sunt voluptas est voluptatem qui dignissimos aut mollitia est aut soluta sequi quo quod atque voluptas dolorum modi harum nam assumenda modi illum consequuntur in iste nihil possimus eum corrupti quibusdam ea rerum dignissimos a consectetur omnis fuga iusto vero numquam aut qui accusamus quo odio aperiam qui et et voluptatem illum dolore dolorem dolores est rerum est cumque et ex nemo distinctio autem sequi molestiae sed cum sint aut est officiis dolores magni a quis repudiandae qui magni quia eaque itaque incidunt sapiente et quis illo.', 7),
(17, 'Deleniti omnis cum.', 'Alias est ut harum iusto nisi perferendis consequuntur nam voluptatem autem tenetur sit quae facere quia vero hic fuga dolorem distinctio sit ratione dolores veniam fugiat iste voluptatem facilis atque nesciunt debitis saepe odio numquam autem vitae expedita laudantium adipisci numquam maxime odit et magnam laboriosam eveniet ut vel fugit at cum voluptatem vitae pariatur ut qui rerum excepturi animi qui velit adipisci sed deserunt recusandae ullam molestiae tempora enim sunt ducimus assumenda cum quaerat laboriosam ad corrupti rem et qui est nulla deleniti praesentium omnis sed sit itaque officia dolorum necessitatibus qui nulla reiciendis unde unde impedit laborum autem expedita consequatur magni architecto eos voluptas natus minus dicta consequuntur repudiandae sed quibusdam et libero dolor voluptatibus quaerat ut et sunt omnis omnis aut incidunt perspiciatis inventore molestiae temporibus rerum fugiat molestias suscipit non doloribus eos enim architecto non quis excepturi cupiditate quaerat aut ducimus quia ipsam maiores illum quo consequatur iure et perspiciatis ea reprehenderit voluptas earum et tempora qui quidem facilis sunt consectetur quia deleniti accusamus praesentium non aspernatur perspiciatis nemo illo alias animi doloremque et et.', 6),
(18, 'Ut est ut quae.', 'Culpa et optio aliquid et est et aspernatur doloribus voluptatum nemo sint aut ducimus inventore expedita dolores voluptatem ut libero autem et non laboriosam nobis eum aut et ea quo odit sed dicta ut rerum mollitia ipsam vitae natus consequatur et sed non itaque consequuntur assumenda omnis itaque molestiae et omnis esse maxime sint omnis impedit et et adipisci pariatur aut iusto rerum quae molestiae eveniet ducimus unde et qui cupiditate quo dolores et ratione iste veritatis et modi aut doloremque vero sint natus et quo quia et dolorum vitae eligendi minima enim labore quo eveniet doloribus vero hic sunt enim ut vel minus omnis nobis et autem est est ut tempora sit expedita aperiam facilis placeat et qui voluptatem totam nisi a blanditiis voluptatem tenetur enim saepe est iusto iure eveniet odio quos ratione.', 4),
(19, 'Excepturi eos.', 'Libero ut sed facere aliquam ab cum porro eaque voluptatem nihil quia non ea consequatur amet rerum ea minus et rerum dolores non voluptates temporibus laboriosam rerum ex et natus quidem autem voluptatum doloremque asperiores est ut ratione qui nostrum corporis laboriosam unde eum et recusandae architecto debitis impedit voluptas id quia vitae impedit voluptatibus aperiam accusantium vero culpa dolorum qui laudantium ea doloremque necessitatibus qui doloremque sed qui dolor soluta dolor omnis consequatur consequatur non quis nobis quaerat aut nesciunt necessitatibus molestias quidem et velit architecto ad occaecati maxime quas et porro voluptas ut repudiandae esse aut officia at sequi quos harum ut eum consequatur consequatur sed illum temporibus unde ullam modi quis et error temporibus consequuntur deserunt deserunt voluptatem dolorem voluptatum beatae praesentium id id ut unde eveniet ipsum earum laboriosam dignissimos enim maiores qui sit praesentium velit dolorum fugiat aut ipsum beatae est inventore inventore quas voluptas consequuntur suscipit aut laborum ut sit fuga exercitationem velit ut dolorum recusandae consequatur adipisci velit hic dicta ullam cum quas ut corrupti magni et illum enim illum commodi quisquam earum culpa quis nemo voluptatum quaerat iste et libero rem ea rerum ut numquam eaque possimus dicta non sed magnam quia non ad magni consequatur nostrum omnis facilis ut ducimus autem et molestiae amet illum iure minima ipsum earum non.', 11),
(20, 'Sint dicta commodi.', 'Sit minus ullam provident dicta eaque ullam ipsum nemo temporibus id dolore autem ut nostrum neque earum optio veniam assumenda consectetur rerum aperiam qui molestias repellat fugiat eos quo quia vero enim dolorum et suscipit repellendus nihil quas ad quam et accusamus ut sed fugit accusantium rerum ratione voluptatibus qui debitis consequatur quasi aut in et id consectetur et rerum est molestias autem voluptates quo aut beatae necessitatibus incidunt quod assumenda nihil et et consequuntur nostrum quam eaque corrupti tempora non dolor fuga necessitatibus autem est a magnam blanditiis consequatur repellat officiis enim quo maxime sed quae molestias exercitationem commodi commodi reprehenderit tempore id architecto alias earum quia aperiam repellendus distinctio alias ut fugiat autem occaecati est eveniet aut et ut quo incidunt repudiandae ducimus sunt ut excepturi nemo rem saepe accusantium est et dolor aut libero quo libero quia magni impedit illum quam aut vel et sequi excepturi adipisci optio illo voluptatem.', 14);

-- --------------------------------------------------------

--
-- Structure de la table `user`
--

CREATE TABLE `user` (
  `id` int(11) NOT NULL,
  `email` varchar(255) NOT NULL,
  `first_name` varchar(255) NOT NULL,
  `last_name` varchar(255) NOT NULL,
  `password` varchar(255) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Déchargement des données de la table `user`
--

INSERT INTO `user` (`id`, `email`, `first_name`, `last_name`, `password`) VALUES
(1, 'henri-bouchet@free.fr', 'Henri', 'Bouchet', '$2y$10$TARmoPuivzP3EJdf.GE4.O2tdX6C3fX5oEfTg5a.H1ue2SWLHbUIS'),
(2, 'alain-valentin@club-internet.fr', 'Alain', 'Valentin', '$2y$10$EuJoK9pzAgI/5j1gmRwpr.EyUojQLGgjm9Oa81B.8lu/7ygDov3zS'),
(3, 'victor-klein@laposte.net', 'Victor', 'Klein', '$2y$10$L8yQ7rIZmwyq5cohQ4V7FuTt3Ege0DGygRCSH32Ye3nL38qoFH1pm'),
(4, 'zacharie-lopes@hotmail.fr', 'Zacharie', 'Lopes', '$2y$10$hW3RdYpoOCH3w0eN6dAONOFSGhhhnjuOn3rseo4APsHQ015vpoPR6'),
(5, 'audrey-navarro@dbmail.com', 'Audrey', 'Navarro', '$2y$10$o0.BkAGjuKdi6Gs84V1tgOUT9hL24RAKlnwtOUJ9aIKlvCBnz0Dda'),
(6, 'yves-ferrand@hotmail.fr', 'Yves', 'Ferrand', '$2y$10$0O1z7tOB6WUVXgSrUNAB8eOGHbRa53nmq0uojFQjBmSoorx7bI2dG'),
(7, 'paul-allain@club-internet.fr', 'Paul', 'Allain', '$2y$10$E3NdiyskLo0GE2MU/gOo3OxOBXqHWLfXTuLtZGX3kiSKIxyxO9uea'),
(8, 'augustin-lacombe@dbmail.com', 'Augustin', 'Lacombe', '$2y$10$sGjI5qmIgdD7/CRt2fYaM.3cli1BZThtZsTiTGxbEZN/9KxVPk/Bu'),
(9, 'christine-faure@club-internet.fr', 'Christine', 'Faure', '$2y$10$ewkepJReDLhldbvMNNtsMOC7XsGciyHv2W9g4JTB7at0BOvB3vbIS'),
(10, 'william-dupuis@club-internet.fr', 'William', 'Dupuis', '$2y$10$yJHfx83YYPSEeE1X/ot6/.AgwH2URCBA9dyzK7XNz7tuMejXcn7jO'),
(11, 'veronique-pineau@gmail.com', 'Véronique', 'Pineau', '$2y$10$GwRML9U8Zhn6NykSMInux.uoKsUqq5KvPEzykTbdun6qCspt9AEbC'),
(12, 'sylvie-potier@dbmail.com', 'Sylvie', 'Potier', '$2y$10$/ttNzTDq2Trt1y4miifTxeYWR3TIcHzMUgBhQ/fTh9I8pLhZf3BFi'),
(13, 'marianne-guerin@club-internet.fr', 'Marianne', 'Guerin', '$2y$10$B2c4CYqWRSz5RVWjFYPHkeXtHOZC47JvqFx980JpeKUY7eKxSr.vq'),
(14, 'suzanne-daniel@gmail.com', 'Suzanne', 'Daniel', '$2y$10$q33QCvOuu3pN0GkVC/WG.u0VpY2NT/Rtj13.xvNwFKerzomhbvbXe'),
(15, 'margaud-dumas@tele2.fr', 'Margaud', 'Dumas', '$2y$10$nlEA3fl/QRA6QfAbX6zOjuYgaVs89cLtjGx7YGozMNr5yHZ0UeMye'),
(16, 'francois-pierre@tele2.fr', 'François', 'Pierre', '$2y$10$ulxARUMIQhE7kGf5lQkkdeTI6mIMvf460gPsM7hYyZRqOmm6/5mmm'),
(17, 'philippe-dufour@wanadoo.fr', 'Philippe', 'Dufour', '$2y$10$cC7hcyGS9jIVysdGnXJ1.O1jKx.puJL7rp2BFuQvzHOkdFEW0VjTG'),
(18, 'augustin-hebert@dbmail.com', 'Augustin', 'Hebert', '$2y$10$T/fIMhm2ODqiMfuEmhtDJulQvHkoypuZL4UFZgShkx1QSbZB0Rc1m'),
(19, 'claire-pichon@hotmail.fr', 'Claire', 'Pichon', '$2y$10$4kR3NbLWzxS1WoW3AJeyJ.Wf83KhSu665RkXRwMwA9aZk1OKGTHOC'),
(20, 'jules-boulay@hotmail.fr', 'Jules', 'Boulay', '$2y$10$wti5BFk9hXc3E/WSK1uzdOMwMv28KC7ocN4L.wrbfo0qtsYeKtVB.');

--
-- Index pour les tables déchargées
--

--
-- Index pour la table `book`
--
ALTER TABLE `book`
  ADD PRIMARY KEY (`id`);

--
-- Index pour la table `user`
--
ALTER TABLE `user`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT pour les tables déchargées
--

--
-- AUTO_INCREMENT pour la table `book`
--
ALTER TABLE `book`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=21;

--
-- AUTO_INCREMENT pour la table `user`
--
ALTER TABLE `user`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=21;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
